config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'lab#input'
  get 'lab/input'
  get 'lab/show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lab_show.rb
# frozen_string_literal: true

class LabShow
  include ActiveModel::Model
  include ActiveModel::Validations

  attr_accessor :numb

  validates :numb, presence: { message: 'не может быть пустым' }
  # validates :numb, format: {with: /\d/, message: 'Пожалуйста, число'}
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/lab_controller.rb
# frozen_string_literal: true

# Controller for main logic
class LabController < ApplicationController
  include LabHelper
  before_action :check_params, only: :show

  def input; end

  def show
    @res = if params[:numb] == ''
             0
           else
             LabHelper.palin([params[:numb]])
           end
  end

  private

  def check_params
    # logic for check for digits
    msg = if params[:numb].nil?
            'Nil class'
          elsif params[:numb].match?(/\D/)
            'Были введены не только цифры'
          end

    redirect_to root_path, notice: msg if msg
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/lab_helper.rb
# frozen_string_literal: true

module LabHelper
  # This method smells of :reek:DuplicateMethodCall%>
  def self.palin(number)
    sum = (number[number.length - 1].to_s.to_i + number[number.length - 1].to_s.reverse.to_i).to_s
    number << sum
    if number.length == 1000
      number
    elsif sum == sum.reverse
      number
    else
      palin(number)
    end
  end
end

app/views/lab/input.html.erb
<h1>Лабораторная работа 8</h1>
<%= form_with url: lab_show_path, method: :get do |form|%>
<%= form.label('Число:')%>
<%= form.number_field(:numb)%>
<%= form.submit('Проверить', id: 'check_button')%>
<% end%>
<br>
<%= flash[:notice]%>

app/views/lab/show.html.erb
<%if @res == 0%>
  <h2>Ошибка! Пусте поле</h2>
<%else%>
    <h1>Результат:</h1>

    <div class="tabled">
        <div class="cap">
            <div class="thead">
                <div class="rowt">
                    <div class="col1">Номер</div>
                    <div class="col2">Результат вычислений</div>
                </div>
            </div>
            <div class = "tbody">
                <%@res.each_index do |index|%>
                  <div class = "rowt">
                    <div class = "col1"><%=index + 1%></div>
                    <div class = "col2"><%=@res[index]%></div>
                  </div>
                <%end%>
            </div>
        </div>
    </div>
    <%if @res.length == 1000%>
        <h3>Для числа <%=@res[0] + ' ' + 'гипотеза не подтверждена'%></h3> 
    <%else%>
        <h3>Для числа <%=@res[0] + ' ' + 'гипотеза подтверждена'%></h3>
    <%end%>
    <h4><%=link_to 'Назад', lab_input_path%></h4>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>